# Generated by Django 4.2.5 on 2023-10-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lockers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lockers.locker')),
                ('receiver', models.ManyToManyField(related_name='receiver', to='customers.customer')),
                ('sender', models.ManyToManyField(related_name='sender', to='customers.customer')),
            ],
        ),
    ]
