# Generated by Django 4.2.5 on 2023-10-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_rename_locker_size_locker_size'),
        ('parcels', '0003_rename_parcel_size_parcel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lockers.locker'),
        ),
    ]
