# Generated by Django 4.2.5 on 2023-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_parcel_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='size',
            field=models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL')]),
        ),
    ]
