# Generated by Django 4.2.5 on 2023-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=128)),
                ('locker_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('out_of_order', 'Out of Order')], default='free', max_length=12)),
            ],
        ),
    ]
