# Generated by Django 4.2.5 on 2023-10-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_alter_locker_locker_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='locker_size',
            new_name='size',
        ),
    ]
